spring.application.name=final-java-project
spring.datasource.url=jdbc:postgresql://localhost:5432/clothing_store_db
spring.datasource.username=postgres
spring.datasource.password=11032007

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true